GCP_SECRET_NAME="gcp-key-drive-v3"
DRIVE_CREDS_NAME="eu-prod-drive-secrets"
AXLE_SECRETS_NAME="axle-prod-secrets"

export DTADMIN_ENV='prod-eu'
export PATH="/venv/bin:$PATH"
export AWS_REGION=eu-central-1
export GOOGLE_APPLICATION_CREDENTIALS='/opt/gcn-key.json'
export TWILIO_BASE_URL="https://admin.drivetrain.ai"
export SLACK_TENANT_ACCESS_CHANNEL="tenant-access-requests"
