GCP_SECRET_NAME="REPLACE_WITH_SECRET_NAME"
DRIVE_CREDS_NAME="REPLACE_WITH_SECRET_NAME"
AXLE_SECRETS_NAME="REPLACE_WITH_SECRET_NAME"

export DTADMIN_ENV='prod-eu'
export PATH="/venv/bin:$PATH"
export AWS_REGION=eu-central-1
export GOOGLE_APPLICATION_CREDENTIALS='/opt/gcn-key.json'
export TWILIO_BASE_URL="https://admin.example.com"
export SLACK_TENANT_ACCESS_CHANNEL="tenant-access-requests"
