GCP_SECRET_NAME="gcp-key"
DRIVE_CREDS_NAME="prod-secrets"
AXLE_SECRETS_NAME="axle-prod-secrets"

export DTADMIN_ENV='prod'
export PATH="/venv/bin:$PATH"
export AWS_REGION=us-east-1
export GOOGLE_APPLICATION_CREDENTIALS='/opt/gcn-key.json'
export TWILIO_BASE_URL="https://admin.drivetrain.ai"
export SLACK_TENANT_ACCESS_CHANNEL="tenant-access-requests"