"""Datadog — real REST API (v2 Users), NOT the generic SCIM client. Datadog's API (SCIM included)
authenticates with TWO headers together (DD-API-KEY + DD-APPLICATION-KEY), not a single bearer token,
so the generic ScimClient (Authorization: Bearer <token>) can never work against it regardless of what
value DATADOG_SCIM_TOKEN holds — confirmed live 2026-09-07. Needs a key pair generated by an account
with User Access Manage (or Admin) permission; a metrics-ingestion-scoped key returns 403 on every
user-management call, also confirmed live that same day."""
import logging

from dtapp.garage.core.config import settings
from dtapp.garage.core.errors import ConfigError, ServiceError
from dtapp.garage.core.http_util import ServiceClient

logger = logging.getLogger(__name__)


class DatadogClient:
    def __init__(self, service_client=None):
        self._client = service_client or ServiceClient(
            "Datadog", base_url="https://api.datadoghq.com/api/v2",
            headers_fn=lambda: {"DD-API-KEY": settings.datadog_api_key,
                                "DD-APPLICATION-KEY": settings.datadog_app_key},
        )

    def _configured(self) -> bool:
        return bool(settings.datadog_api_key and settings.datadog_app_key)

    def _dryrun(self, op, payload):
        logger.info("[access] DRYRUN datadog %s — would send: %s", op, payload)
        return {"dryrun": True, "op": op}

    def _require_config(self):
        if self._configured():
            return False
        if settings.dryrun_unconfigured:
            return True
        raise ConfigError("Datadog: datadog_api_key/datadog_app_key not configured")

    def _find_by_email(self, email: str):
        resp = self._client.get("/users", params={"filter": email})
        for u in resp.get("data", []):
            if (u.get("attributes", {}).get("email") or "").lower() == email.lower():
                return u
        return None

    def invite_member(self, email: str, name: str = "") -> dict:
        """POST /users — creates and auto-invites in one call. NOT live-tested (would create a real
        seat) — implemented per Datadog's documented v2 Users API shape; confirm on first real use."""
        if self._require_config():
            return self._dryrun("invite_member", {"email": email})
        return self._client.post("/users", json={
            "data": {"type": "users", "attributes": {"email": email, "name": name or email.split("@")[0]}},
        })

    def remove_member(self, email: str) -> None:
        """DELETE /users/{id} — disables the account (Datadog has no hard-delete; this is the real
        offboard action, confirmed live 2026-09-07 on a real employee: disabled=True, status=Disabled)."""
        if self._require_config():
            self._dryrun("remove_member", {"email": email})
            return
        user = self._find_by_email(email)
        if user:
            self._client.delete(f"/users/{user['id']}")

    def get_user_status(self, email: str) -> str:
        if self._require_config():
            return "removed"
        user = self._find_by_email(email)
        if not user:
            return "removed"
        return "removed" if user.get("attributes", {}).get("disabled") else "active"


datadog_client = DatadogClient()
